
[font]
normal = { family = "MesloLGSNerdFontMono", style = "Regular" }
bold = { family = "MesloLGSNerdFontMono", style = "Bold" }
italic = { family = "MesloLGSNerdFontMono", style = "Italic" }
bold_italic = { family = "MesloLGSNerdFontMono", style = "BoldItalic" }
size = 10

[general]
import = [
    "~/.config/alacritty/tokyo-night-alacritty-theme/tokyo-night.toml",
]
